name = "ActiveSpaceSolvers"
uuid = "f8e94ea7-44cc-4f7e-92b7-2a8da6f47aca"
authors = ["Nick Mayhall <nmayhall@vt.edu> and contributors"]
version = "0.1.0"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockDavidson = "b4c031f8-e7c9-4879-896c-063a10ff8103"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
InCoreIntegrals = "d8079e1f-d74b-4a3d-abb0-c0b53e3a8379"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
QCBase = "0dbae682-d491-4cbc-9a73-7148926f1b63"
RDM = "e382014c-6717-46ba-99dc-880f59d7a5e4"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
julia = "â‰¥ 1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
